replicaCount: 2

image:
  repository: gauri1601/go-web-app
  pullPolicy: IfNotPresent
  tag: last

ingress:
  enabled: true
  classname: ""
  annotations: {}
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix
